spring:
  application:
    name: work-kg-backend

  datasource:
    url: jdbc:postgresql://postgres-duve.railway.internal:5432/railway
    username: postgres
    password: KCLQJyHRjAzTHZvJJuRpQpnRFBmBaTJo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    time-zone: Asia/Bishkek
    date-format: yyyy-MM-dd'T'HH:mm:ss

server:
  port: 8080

jwt:
  secret: your-256-bit-secret-key-change-this-in-production
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000

telegram:
  bot:
    token: 8288728857:AAFvrR2fDp9y1WQg-lv1CvCAO3A41N6rlBk

finik:
  api-key: 6t50mJl6wz37FvP9Cg9sV5iB7Jpt6BaS9raiLDwo
  account-id: e9454d9b-a85f-4678-9a5c-2819fedbce2e
  private-key-path: classpath:finik_private.pem
  base-url: https://beta.api.acquiring.averspay.kg
  merchant-category-code: "0742"
  qr-name-en: "Bilgirim - Testing"
  webhook-url: ${APP_BASE_URL}/api/webhooks/finik


logging:
  level:
    kg.workkg: DEBUG
    org.hibernate.SQL: DEBUG